{
 "title": "Monitor",
 "time": { "from": "2025-10-02T05:46:12.933Z", "to": "2025-10-02T10:35:11.997Z" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  MetricName,\n  avg(Value) * 100 AS avg_pct,\n  toDateTime64( toUInt64( TimeUnix ) / 60 * 60, 9 ) AS minute_bucket\nFROM default.otel_metrics_gauge\nWHERE MetricName = 'system.cpu.usage'\n  AND TimeUnix >= now() - INTERVAL 1 MINUTE\nGROUP BY MetricName, minute_bucket\nORDER BY minute_bucket DESC, MetricName;"
    }
   ]
  },
  {
   "title": "RPS (Request Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfSecond(Timestamp) AS sec,\n    count() AS requests_per_sec\nFROM default.otel_traces\nWHERE SpanName LIKE '%/api/%'\nGROUP BY sec\nORDER BY sec;"
    }
   ]
  },
  {
   "title": "Logs Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(Timestamp, INTERVAL 1 HOUR) AS time_interval,\n    SeverityText,\n    COUNT(*) AS log_count\nFROM default.otel_logs\nWHERE SeverityText IN ('INFO', 'ERROR', 'WARN')\nGROUP BY time_interval, SeverityText\nORDER BY time_interval DESC, SeverityText"
    }
   ]
  },
  {
   "title": "Error Tracker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(Timestamp, INTERVAL 1 HOUR) AS time_interval,\n    SeverityText,\n    COUNT(*) AS error_count\nFROM default.otel_logs\nWHERE SeverityText = 'ERROR'\nGROUP BY time_interval, SeverityText\nORDER BY time_interval DESC, SeverityText"
    }
   ]
  },
  {
   "title": "CPU Thresholds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  MetricName,\n  avg(Value) * 100 AS avg_pct,\n  toDateTime64( toUInt64( TimeUnix ) / 60 * 60, 9 ) AS minute_bucket\nFROM default.otel_metrics_gauge\nWHERE MetricName IN ('system.cpu.usage', 'process.cpu.usage')\nGROUP BY MetricName, minute_bucket\nORDER BY minute_bucket DESC, MetricName;"
    }
   ]
  },
  {
   "title": "Mean Response Time:  50, 75, 95, 99 Percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, INTERVAL 1 MINUTE) AS minute,\n  avg(Duration / 1000000) AS mean,\n  quantileExact(0.50)(Duration / 1000000) AS p50_ms,\n  quantileExact(0.75)(Duration / 1000000) AS p75_ms,\n  quantileExact(0.95)(Duration / 1000000) AS p95_ms,\n  quantileExact(0.99)(Duration / 1000000) AS p99_ms\nFROM default.otel_traces\nWHERE SpanName LIKE '%/api/%'\nGROUP BY minute\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Top Requests",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n    SpanName,\n    COUNT(*) AS cnt\nFROM default.otel_traces\nWHERE SpanName LIKE '%/api/%'\nGROUP BY SpanName\nORDER BY cnt DESC"
    }
   ]
  },
  {
   "title": "Heap Memory Usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Подзапрос для агрегации каждой метрики по временным бакетам\nWITH\n  agg AS (\n    SELECT\n      MetricName,\n      toDateTime64(toUInt64(TimeUnix) / 60 * 60, 9) AS minute_bucket,\n      avg(Value) AS avg_value\n    FROM default.otel_metrics_gauge\n    WHERE MetricName IN (\n      'jvm.memory.committed',\n      'jvm.memory.max',\n      'jvm.memory.usage.after.gc',\n      'jvm.memory.used'\n    )\n    GROUP BY MetricName, minute_bucket\n  )\n\nSELECT\n  a.minute_bucket,\n  maxIf(a.avg_value, a.MetricName = 'jvm.memory.used') / 1024 / 1024 AS used_mib,\n  maxIf(a.avg_value, a.MetricName = 'jvm.memory.max') / 1024 / 1024 AS max_mem_mib,\n  maxIf(a.avg_value, a.MetricName = 'jvm.memory.committed') / 1024 / 1024 AS committed_mib,\n  maxIf(a.avg_value, a.MetricName = 'jvm.memory.usage.after.gc') / 1024 / 1024  AS usage_after_gc_mib,\n  -- вычисление процента использования: used / max_mem * 100\n  if(max_mem_mib > 0,\n     (maxIf(a.avg_value, a.MetricName = 'jvm.memory.used') / max_mem_mib) * 100,\n     NULL\n  ) AS used_pct_of_max,\n  -- другое отношение: used / committed * 100\n  if(committed_mib > 0,\n     (maxIf(a.avg_value, a.MetricName = 'jvm.memory.used') / committed_mib) * 100,\n     NULL\n  ) AS used_pct_of_committed\nFROM agg a\nGROUP BY a.minute_bucket\nORDER BY a.minute_bucket DESC;"
    }
   ]
  }
 ]
}