name: Deploy Backend to Beget

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Beget
    
    steps:
    - name: Checkout production branch
      uses: actions/checkout@v4
      with:
        ref: production
    
    - name: Deploy to Beget via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.BEGET_SSH_HOST }}
        username: ${{ secrets.BEGET_SSH_USER }}
        password: ${{ secrets.BEGET_SSH_PASSWORD }}
        source: "src/main/java/"
        target: ${{ secrets.BEGET_DEPLOY_PATH }}
        overwrite: true
        strip_components: 3

    - name: Restart application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BEGET_SSH_HOST }}
        username: ${{ secrets.BEGET_SSH_USER }}
        password: ${{ secrets.BEGET_SSH_PASSWORD }}
        script: |
          cd /root/schedule-parse-system/
          bash restart-services.sh
